# Generated by Django 5.0 on 2023-12-14 15:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiasUteis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                ("modificado", models.DateField(auto_now=True, verbose_name="Criação")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        default=1,
                        verbose_name="Mes",
                    ),
                ),
                ("ano", models.IntegerField(default=2024, verbose_name="Ano")),
                ("qtd_du", models.IntegerField(verbose_name="Dias Úteis")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "vr_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=45.0,
                        max_digits=5,
                        verbose_name="Vale Refeição",
                    ),
                ),
                (
                    "vt_dia",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Vale Transporte"
                    ),
                ),
                (
                    "cor_grafico",
                    models.CharField(
                        default="#000000", max_length=7, verbose_name="Cor no Gráfico"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Frequencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado", models.DateField(auto_now_add=True, verbose_name="Criação")),
                ("modificado", models.DateField(auto_now=True, verbose_name="Criação")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "mes_referencia",
                    models.IntegerField(
                        choices=[
                            (1, "Janeiro"),
                            (2, "Fevereiro"),
                            (3, "Março"),
                            (4, "Abril"),
                            (5, "Maio"),
                            (6, "Junho"),
                            (7, "Julho"),
                            (8, "Agosto"),
                            (9, "Setembro"),
                            (10, "Outubro"),
                            (11, "Novembro"),
                            (12, "Dezembro"),
                        ],
                        default=1,
                        verbose_name="Mes",
                    ),
                ),
                (
                    "ano_referencia",
                    models.IntegerField(default=2024, verbose_name="Ano"),
                ),
                (
                    "qtd_home_office",
                    models.IntegerField(verbose_name="Quantidade de Home Office"),
                ),
                (
                    "qtd_faltas",
                    models.IntegerField(verbose_name="Quantidade de Faltas"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
