# Generated by Django 5.0 on 2023-12-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="vt_dia",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Vale Transporte",
            ),
        ),
    ]
