# Generated by Django 5.0 on 2023-12-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="vr_dia",
            field=models.DecimalField(
                decimal_places=2,
                default=45.0,
                max_digits=5,
                verbose_name="Vale Refeição",
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="vt_dia",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Vale Transporte"
            ),
        ),
    ]
