# Generated by Django 5.0 on 2023-12-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_equipe_vr_dia_alter_equipe_vt_dia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diasuteis",
            name="ano_mes",
        ),
        migrations.AddField(
            model_name="diasuteis",
            name="ano",
            field=models.IntegerField(default=2023, verbose_name="Ano"),
        ),
        migrations.AddField(
            model_name="diasuteis",
            name="mes",
            field=models.IntegerField(
                choices=[
                    (1, "Janeiro"),
                    (2, "Fevereiro"),
                    (3, "Março"),
                    (4, "Abril"),
                    (5, "Maio"),
                    (6, "Junho"),
                    (7, "Julho"),
                    (8, "Agosto"),
                    (9, "Setembro"),
                    (10, "Outubro"),
                    (11, "Novembro"),
                    (12, "Dezembro"),
                ],
                default=1,
                verbose_name="Mes",
            ),
        ),
        migrations.AddField(
            model_name="frequencia",
            name="ano_referencia",
            field=models.IntegerField(default=2023, verbose_name="Ano"),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="mes_referencia",
            field=models.IntegerField(
                choices=[
                    (1, "Janeiro"),
                    (2, "Fevereiro"),
                    (3, "Março"),
                    (4, "Abril"),
                    (5, "Maio"),
                    (6, "Junho"),
                    (7, "Julho"),
                    (8, "Agosto"),
                    (9, "Setembro"),
                    (10, "Outubro"),
                    (11, "Novembro"),
                    (12, "Dezembro"),
                ],
                default=1,
                verbose_name="Mes",
            ),
        ),
    ]
