# Generated by Django 5.0 on 2023-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_usuario_vt_dia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="vt_dia",
            field=models.DecimalField(
                decimal_places=2,
                default=8.8,
                max_digits=5,
                verbose_name="Vale Transporte",
            ),
        ),
    ]
