# Generated by Django 5.0 on 2023-12-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_diasuteis_ano_mes_diasuteis_ano_diasuteis_mes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diasuteis",
            name="ano",
            field=models.IntegerField(default=2024, verbose_name="Ano"),
        ),
        migrations.AlterField(
            model_name="frequencia",
            name="ano_referencia",
            field=models.IntegerField(default=2024, verbose_name="Ano"),
        ),
    ]
