# Generated by Django 5.0 on 2023-12-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_diasuteis_ano_alter_frequencia_ano_referencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="cor_grafico",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="Cor no Gráfico"
            ),
        ),
    ]
